server:
  port: 8080
  servlet:
    context-path: /service1
spring:
  application:
    name: service1

logging:
  config: classpath:customLog.xml

service2:
  url: http://localhost:8081/service2/api/v1
service3:
  url: http://localhost:8082/service3/api/v1
  